#
# Cookbook Name:: collectd-custom
# Recipe:: plugins
#
# Installs the base plugins defined in the node attributes and deletes the old ones
#

plugins = node['collectd-custom']['plugins']
plugins.each do |name, plugin|
  next if %w(syslog logfile).include?(name) # don't generate conf files for loggers, we did that in default

  collectd_plugin name do
    template plugin['template'] || nil
    cookbook plugin['cookbook'] || nil
    options plugin['config']
  end
end

ruby_block "delete_old_plugins" do
  block do
    Dir['/data/collectd.d/*.conf'].each do |path|
      autogen = false
      File.open(path).each_line do |line|
        if line.start_with?('#') and line.include?('autogenerated')
          autogen = true
          break
        end
      end
      if autogen
        begin
          resources(:template => path)
        rescue ArgumentError, Chef::Exceptions::ResourceNotFound
          # If the file is autogenerated and has no template it has likely been removed from the run list
          Chef::Log.info("Deleting old plugin config at #{path}")
          File.unlink(path)
        end
      end
    end
  end
end
