default_statistics_target("100")
max_fsm_pages("500000") 
max_fsm_relations("10000") 
logging_collector("on")
log_rotation_age("1d")
log_rotation_size("100MB")
checkpoint_timeout("5min")
checkpoint_completion_target ("0.5")
checkpoint_warning ("30s")
checkpoint_segments ("10")
wal_buffers ("8MB")
wal_writer_delay ("200ms")
max_stack_depth ("8MB")
total_memory(`cat /proc/meminfo`.scan(/^MemTotal:\s+(\d+)\skB$/).flatten.first.to_i * 1024)
total_memory_mb(total_memory / 1024 / 1024)
shared_memory_percentage("0.25")
effective_cache_size_percentage("0.80")
shared_buffers1(total_memory_mb * shared_memory_percentage.to_f)
shared_buffers(shared_buffers1.to_i)
sysctl_shared_buffers(total_memory)
effective_cache_size1(total_memory_mb * effective_cache_size_percentage.to_f)
effective_cache_size(effective_cache_size1.to_i)
if total_memory < 5147483648
    maintenance_work_mem ("128MB")
    work_mem ("32MB")
else
    maintenance_work_mem("256MB")
    work_mem ("64MB")
end
